#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""{}

LICENSE

{}

REPO

{}

USAGE

{}

WARNING

{}

NOTES

{}

"""

from __future__ import absolute_import, division, print_function, with_statement

# Manual entry

creator = "Matt Busby"
email = "@idrmhyprbls"
created = "1 June, 2015"
contributors = "N/a"
credits = "N/a"

program = "pyrochess"
project = "https://github.com/idrmhyprbls/PyroChess"
brief = "A shi**y chess engine forged in the fires of Python awesomeness."

compiler = "N/a"
python = "2.7.11"
os = "Fedora Linux 24, 64bit"

usage = """\
`python %.py`
`./%.py # if executable`
`nosetests %.py`"""
warning = "N/a"
notes = "Run all modules through pyflakes, pylint, & pydoc"

# Autogenerated

author = "{} {}".format(creator, email)

version = "?.?.?"
date = "??/????"
try:
    # Version info must be in ./RELEASE.md !!
    with open('./RELEASE.md') as ifile:
        import re
        for each in ifile:
            match = re.search(
                    '([0-9]{1,2}\.){2}[0-9]{1,2}\s+[0-9]{1,2}/[0-9]{2,4}',
                    each)
            if match:
                version, date = match.group().split()
                break
        del re
except:
    pass
else:
    del ifile

license = "BSD-3-Clause"
try:
    # License and Copyright MUST be update in ../LICENSE !!
    with open('./LICENSE') as ifile:
        license = "".join(ifile.readlines())
except:
    pass
else:
    del ifile

copyright = ""
for line in license.split():
    if 'copyright' in line.lower():
        copyright = line.strip()
        break
del line

# Docstring

__doc__ = __doc__.format(brief, license, project, usage, warning, notes)
