# Manual entry

__creator__ = "Matt Busby"
__email__ = "@idrmhyprbls"
__created__ = "1 June, 2015"
__contributors__ = "N/a"
__credits__ = "N/a"

__version__ = "0.1.1"
__date__ = "June, 2016"
__program__ = "pyrochess"
__project__ = "https://github.com/idrmhyprbls/PyroChess"

__compiler__ = "N/a"
__python__ = "2.7.7"
__os__ = "Fedora Linux 21, 64bit"

__usage__ = """\
`python %.py`
`./%.py # if executable`
`nosetests %.py`"""
__warning__ = "N/a"
__notes__ = "Run all modules through pyflakes, pylint, & pydoc"

# Autogenerated

__author__ = "{} {}".format(__creator__, __email__)

try:
    with open('./LICENSE') as ifile:
        __license__ = "".join(ifile.readlines())
except:
        __license__ = "BSD-3-Clause"
else:
    del ifile

__copyright__ = ""
for line in __license__.split():
    if 'copyright' in line.lower():
        __copyright__ = line.strip()
        break
del line
